build:
    environment:
        php:
            version: "7.4"
    nodes:
        my-tests-with-coverage:
            tests:
                override:
                - command: ./vendor/bin/phpunit --configuration .phpunit.xml
                  coverage:
                    file: build/coverage.clover
                    format: php-clover