imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
  environment:
    php: 7.4
  dependencies:
    before:
      -
        command: "mkdir build"

  tests:
      override: 
          -
              command: "make test"
              coverage:
                  file: "build/coverage.clover"
                  format: "php-clover"