imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
  environment:
    php: v7.4
  dependencies:
    before:
      -
        command: "mkdir build"

    tests:
        override: 
            -
                command: "./vendor/bin/phpunit test --configuration .phpunit.xml"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"