filter:
    excluded_paths: [vendor/*, test/*]

build:

    nodes:
        my-tests-with-coverage:
        tests:
            override:
            - command: make test
                coverage:
                file: build/coverage.clover
                format: php-clover