build:
    environment:
        php:
            version: "7.4"
    nodes:
        my-tests-with-coverage:
            tests:
                override:
                - command: make test
                    coverage:
                    file: build/coverage.clover
                    format: php-clover