build:
    environment:
        php:
            version: "7.4"
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        my-tests-with-coverage:
            tests:
                override:
                - php-scrutinizer-run
                - command: ./vendor/bin/phpunit --configuration .phpunit.xml
                  coverage:
                    file: build/coverage.clover
                    format: php-clover