language: php

php:
  - "7.4"

sudo: false

before_script:
  - composer install
  - composer selfupdate
  - rsync -av vendor/jomi19/anaxrem/test/ test/
  - rsync -av vendor/jomi19/anaxrem/src/ src/
  - rsync -av vendor/jomi19/anaxrem/config/ config/

script:
  - make test

